##### BASE STAGE #####
FROM node:lts-bookworm-slim AS base

# Set working directory
WORKDIR /app

# Install corepack
RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.shrc" SHELL="$(which sh)" sh -
  # Enable pnpm
  ENV PNPM_HOME="/pnpm"
  ENV PATH="$PNPM_HOME:$PATH"
  RUN corepack enable
  RUN corepack install -g pnpm@latest
  RUN corepack prepare pnpm@latest --activate

# Install dependencies
COPY package.json ./
RUN pnpm install

COPY . .

# Entrypoint
CMD ["/bin/sh", "-c", "[ ! -d node_modules ] && pnpm install; pnpm run dev"]