name: TSC and Lint for Qwik City App

on:
  # push:
  #   branches: [dev]
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  tsc-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run TypeScript type check
        run: pnpm run build.types

      - name: Run ESLint
        run: pnpm run lint
